# Generated by Django 5.0.6 on 2024-05-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtmAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=255, null=True)),
                ('english_address', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=255, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'atm_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtmMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm_code', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=10, null=True)),
                ('atm_name', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=500, null=True)),
                ('type', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=500, null=True)),
                ('category', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=500, null=True)),
                ('atm_install', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=500, null=True)),
                ('phone', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=200, null=True)),
                ('service_type', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=500, null=True)),
                ('use_wheel', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=100, null=True)),
                ('voice', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=100, null=True)),
            ],
            options={
                'db_table': 'atm_main',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TwPopulation',
            fields=[
                ('city_town_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=3, null=True)),
                ('town', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=4, null=True)),
                ('population', models.IntegerField()),
                ('area', models.FloatField()),
                ('density', models.IntegerField()),
            ],
            options={
                'db_table': 'tw_population',
                'managed': False,
            },
        ),
    ]
