# Generated by Django 5.0.6 on 2024-06-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_town_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=3, null=True)),
                ('town', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=4, null=True)),
                ('population', models.IntegerField()),
                ('area', models.FloatField()),
                ('density', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'tw_population',
                'db_table': 'tw_population',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TwPopulation',
        ),
        migrations.AlterModelOptions(
            name='atmaddress',
            options={'managed': False, 'verbose_name_plural': 'atm_address'},
        ),
        migrations.AlterModelOptions(
            name='atmmain',
            options={'managed': False, 'verbose_name_plural': 'atm_main'},
        ),
    ]
