# Generated by Django 5.0.6 on 2024-06-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_city_delete_twpopulation_alter_atmaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False, 'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
    ]
