# Generated by Django 5.0.6 on 2024-06-03 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0005_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='atm.customer')),
            ],
            options={
                'verbose_name_plural': 'Transaction',
                'db_table': 'Transaction',
            },
        ),
    ]
